#!/bin/bash
export DEBIAN_FRONTEND=noninteractive
clear
if [ "$(whoami)" != "root" ]; then
    echo -e "\033[1;33m[\033[1;31mErro\033[1;33m] \033[1;37m- \033[1;33mvocê precisa executar como root\033[0m"
    exit 0
fi

# ==========================================================
# Ubuntu 20, 22, 24 အတွက် Websocket Port အလိုလိုပွင့်ရန် Python Fix နှင့် Domain တောင်းသည့်စနစ်
# ==========================================================
echo -e "\033[1;33m[!] Installing Python Fix for Websocket (Ubuntu 20/22/24)...\033[0m"
apt-get update -yq > /dev/null 2>&1
apt-get install -yq -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" python2 python3 screen dos2unix net-tools wget > /dev/null 2>&1
rm -rf /usr/bin/python
ln -s /usr/bin/python2 /usr/bin/python

clear
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[1;32m◈ Domain (သို့) Subdomain ထည့်သွင်းလိုပါသလား? (y/n)\033[0m"
read -p "➔ ရွေးချယ်ရန် [y/n]: " add_domain
if [[ "$add_domain" == "y" || "$add_domain" == "Y" ]]; then
    read -p "➔ သင့် Domain ကို ရိုက်ထည့်ပါ: " user_domain
    echo "$user_domain" > /etc/domain
    echo -e "\033[1;33m✅ Domain မှတ်သားပြီးပါပြီ!\033[0m"
else
    echo -e "\033[1;31m❌ Domain မထည့်သွင်းပါ။ IP ကိုသာ အသုံးပြုပါမည်。\033[0m"
    rm -rf /etc/domain
fi
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
sleep 2

# GitHub ကနေ menu ဖိုင်ကို auto ဒေါင်းပြီး /bin ထဲ ထည့်ပေးမယ် (ဒါမှ menu command run လို့ရမှာပါ)
wget -qO /bin/menu https://raw.githubusercontent.com/zaw-myscript/ZAW2026-VPN-SSHSCRIPT/refs/heads/main/menu
chmod +x /bin/menu
dos2unix /bin/menu > /dev/null 2>&1

# ပင်မ Menu ကို တန်းဖွင့်ခိုင်းလိုက်ပြီ
menu
