#!/bin/bash
IP=$(cat /etc/IP)
cor1='\033[41;1;37m'
cor2='\033[44;1;37m'
scor='\033[0m'

newclient() {
    cp /etc/openvpn/client-common.txt ~/$1.ovpn
    echo "<ca>" >>~/$1.ovpn
    cat /etc/openvpn/easy-rsa/pki/ca.crt >>~/$1.ovpn
    echo "</ca>" >>~/$1.ovpn
    echo "<cert>" >>~/$1.ovpn
    cat /etc/openvpn/easy-rsa/pki/issued/$1.crt >>~/$1.ovpn
    echo "</cert>" >>~/$1.ovpn
    echo "<key>" >>~/$1.ovpn
    cat /etc/openvpn/easy-rsa/pki/private/$1.key >>~/$1.ovpn
    echo "</key>" >>~/$1.ovpn
    echo "<tls-auth>" >>~/$1.ovpn
    cat /etc/openvpn/ta.key >>~/$1.ovpn
    echo "</tls-auth>" >>~/$1.ovpn
}

fun_geraovpn() {
    [[ "$respost" = @(s|S) ]] && {
        cd /etc/openvpn/easy-rsa/
        ./easyrsa build-client-full $username nopass
        newclient "$username"
        sed -e "s;auth-user-pass;<auth-user-pass>\n$username\n$password\n</auth-user-pass>;g" /root/$username.ovpn >/root/tmp.ovpn && mv -f /root/tmp.ovpn /root/$username.ovpn
    } || {
        cd /etc/openvpn/easy-rsa/
        ./easyrsa build-client-full $username nopass
        newclient "$username"
    }
} >/dev/null 2>&1

clear
echo -e "\E[44;1;37m           CRIAR USUARIO SSH           \E[0m"
echo ""
echo -ne "\033[1;32mInforme o Nome: \033[1;37m"; read nome
while [[ -z $nome ]]; do
    echo -e "\n\033[1;31mNome Invalido!\033[0m"
    echo -ne "\033[1;32mInforme o Nome: \033[1;37m"; read nome
done
echo -ne "\033[1;32mInforme a Senha: \033[1;37m"; read senha
while [[ -z $senha ]]; do
    echo -e "\n\033[1;31mSenha Invalida!\033[0m"
    echo -ne "\033[1;32mInforme a Senha: \033[1;37m"; read senha
done
echo -ne "\033[1;32mInforme o Limite de Conexoes: \033[1;37m"; read limite
while [[ -z $limite ]] || [[ ! $limite =~ ^[0-9]+$ ]]; do
    echo -e "\n\033[1;31mLimite Invalido!\033[0m"
    echo -ne "\033[1;32mInforme o Limite de Conexoes: \033[1;37m"; read limite
done
echo -ne "\033[1;32mInforme os Dias de Validade: \033[1;37m"; read dias
while [[ -z $dias ]] || [[ ! $dias =~ ^[0-9]+$ ]]; do
    echo -e "\n\033[1;31mDias Invalidos!\033[0m"
    echo -ne "\033[1;32mInforme os Dias de Validade: \033[1;37m"; read dias
done

validade=$(date '+%C%y-%m-%d' -d " +$dias days")
validade2=$(date '+%d/%m/%Y' -d " +$dias days")

echo -e "\n\033[1;33mCRIANDO USUARIO $nome...\033[0m"
useradd -M -s /bin/false -e $validade $nome > /dev/null 2>&1
echo "$nome:$senha" | chpasswd > /dev/null 2>&1
echo "$nome $limite" >> /root/usuarios.db
sleep 1.5

clear
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[1;32m◈ Host / IP   :⪧\033[1;37m  $IP"
echo -e "\033[1;32m◈ Username    :⪧\033[1;37m  $nome"
echo -e "\033[1;32m◈ Password    :⪧\033[1;37m  $senha"
echo -e "\033[1;32m◈ Login Limit :⪧\033[1;37m  $limite"
echo -e "\033[1;32m◈ Expire Date :⪧\033[1;37m  $validade2"
echo -e ""
echo -e "     \033[1;35m◈──────⪧ PORTS ⪦ ───────◈\033[0m"
echo -e ""
echo -e "\033[1;33m◈ SSH      ⌁\033[1;37m  22"
echo -e "\033[1;33m◈ SSL      ⌁\033[1;37m  443"
echo -e "\033[1;33m◈ Squid    ⌁\033[1;37m  8080"
echo -e "\033[1;33m◈ DropBear ⌁\033[1;37m  80"
echo -e "\033[1;33m◈ BadVPN   ⌁\033[1;37m  7300"
echo -e ""
echo -e "   \033[1;35m◈───⪧ONLINE USER COUNT⪦────◈\033[0m"
echo -e ""
echo -e " \033[1;36mhttp://$IP:8888/server/online\033[0m"
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo ""
