#!/bin/bash
#====================================================
#	@kiritosshxd
#====================================================
IP=$(cat /etc/IP)
cor1='\033[41;1;37m'
cor2='\033[44;1;37m'
scor='\033[0m'

# Gerar client.ovpn
newclient() {
    cp /etc/openvpn/client-common.txt ~/$1.ovpn
    echo "<ca>" >>~/$1.ovpn
    cat /etc/openvpn/easy-rsa/pki/ca.crt >>~/$1.ovpn
    echo "</ca>" >>~/$1.ovpn
    echo "<cert>" >>~/$1.ovpn
    cat /etc/openvpn/easy-rsa/pki/issued/$1.crt >>~/$1.ovpn
    echo "</cert>" >>~/$1.ovpn
    echo "<key>" >>~/$1.ovpn
    cat /etc/openvpn/easy-rsa/pki/private/$1.key >>~/$1.ovpn
    echo "</key>" >>~/$1.ovpn
    echo "<tls-auth>" >>~/$1.ovpn
    cat /etc/openvpn/ta.key >>~/$1.ovpn
    echo "</tls-auth>" >>~/$1.ovpn
}

fun_geraovpn() {
    [[ "$respost" = @(s|S) ]] && {
        cd /etc/openvpn/easy-rsa/
        ./easyrsa build-client-full $username nopass
        newclient "$username"
        sed -e "s;auth-user-pass;<auth-user-pass>\n$username\n$password\n</auth-user-pass>;g" /root/$username.ovpn >/root/tmp.ovpn && mv -f /root/tmp.ovpn /root/$username.ovpn
    } || {
        cd /etc/openvpn/easy-rsa/
        ./easyrsa build-client-full $username nopass
        newclient "$username"
    }
} >/dev/null 2>&1

[[ -e /etc/openvpn/server.conf ]] && {
    _Port=$(grep -w 'port' /etc/openvpn/server.conf | awk {'print $2'})
    hst=$(sed -n '8 p' /etc/openvpn/client-common.txt | awk {'print $4'})
    rmt=$(sed -n '7 p' /etc/openvpn/client-common.txt)
    hedr=$(sed -n '8 p' /etc/openvpn/client-common.txt)
    prxy=$(sed -n '9 p' /etc/openvpn/client-common.txt)
    rmt2='/SSHPLUS?'
    rmt3='www.vivo.com.br 8088'
    prx='200.142.130.104'
    payload1='#payload "HTTP/1.0 [crlf]Host: m.youtube.com[crlf]CONNECT HTTP/1.0[crlf][crlf]|[crlf]"'
    payload2='#payload "CONNECT 127.0.0.1:1194[split][crlf] HTTP/1.0 [crlf][crlf]#"'
    vivo1="portalrecarga.vivo.com.br/recarga"
    vivo2="portalrecarga.vivo.com.br/controle/"
    vivo3="navegue.vivo.com.br/pre/"
    vivo4="navegue.vivo.com.br/controle/"
    vivo5="www.vivo.com.br"
    oi="d1n212ccp6ldpw.cloudfront.net"
    bypass="net_gateway"
    cert01="/etc/openvpn/client-common.txt"
    if [[ "$hst" == "$vivo1" ]]; then
        Host="Portal Recarga"
    elif [[ "$hst" == "$vivo2" ]]; then
        Host="Recarga contole"
    elif [[ "$hst" == "$vivo3" ]]; then
        Host="Portal Navegue"
    elif [[ "$hst" == "$hst" == "$vivo4" ]]; then
        Host="Nav controle"
    elif [[ "$hst" == "$IP:$_Port" ]]; then
        Host="Vivo MMS"
    elif [[ "$hst" == "$oi" ]]; then
        Host="Oi"
    elif [[ "$hst" == "$bypass" ]]; then
        Host="Modo Bypass"
    elif [[ "$hedr" == "$payload1" ]]; then
        Host="OPEN SOCKS"
    elif [[ "$hedr" == "$payload2" ]]; then
        Host="OPEN SQUID"
    else
        Host="Customizado"
    fi
}

clear
echo -e "\E[44;1;37m           CRIAR USUARIO SSH           \E[0m"
echo ""
echo -ne "\033[1;32mInforme o Nome: \033[1;37m"; read nome
while [[ -z $nome ]]; do
    echo -e "\n\033[1;31mNome Invalido!\033[0m"
    echo -ne "\033[1;32mInforme o Nome: \033[1;37m"; read nome
done
echo -ne "\033[1;32mInforme a Senha: \033[1;37m"; read senha
while [[ -z $senha ]]; do
    echo -e "\n\033[1;31mSenha Invalida!\033[0m"
    echo -ne "\033[1;32mInforme a Senha: \033[1;37m"; read senha
done
echo -ne "\033[1;32mInforme o Limite de Conexoes: \033[1;37m"; read limite
while [[ -z $limite ]] || [[ ! $limite =~ ^[0-9]+$ ]]; do
    echo -e "\n\033[1;31mLimite Invalido!\033[0m"
    echo -ne "\033[1;32mInforme o Limite de Conexoes: \033[1;37m"; read limite
done
echo -ne "\033[1;32mInforme os Dias de Validade: \033[1;37m"; read dias
while [[ -z $dias ]] || [[ ! $dias =~ ^[0-9]+$ ]]; do
    echo -e "\n\033[1;31mDias Invalidos!\033[0m"
    echo -ne "\033[1;32mInforme os Dias de Validade: \033[1;37m"; read dias
done

validade=$(date '+%C%y-%m-%d' -d " +$dias days")
validade2=$(date '+%d/%m/%Y' -d " +$dias days")

# Criação do usuário no sistema
useradd -M -s /bin/false -e $validade $nome
echo "$nome:$senha" | chpasswd
echo "$nome $limite" >> /root/usuarios.db

clear
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[1;32m◈ Host / IP   :⪧\033[1;37m  $IP"
echo -e "\033[1;32m◈ Username    :⪧\033[1;37m  $nome"
echo -e "\033[1;32m◈ Password    :⪧\033[1;37m  $senha"
echo -e "\033[1;32m◈ Login Limit :⪧\033[1;37m  $limite"
echo -e "\033[1;32m◈ Expire Date :⪧\033[1;37m  $validade2"
echo -e ""
echo -e "     \033[1;35m◈──────⪧ PORTS ⪦ ───────◈\033[0m"
echo -e ""
echo -e "\033[1;33m◈ SSH      ⌁\033[1;37m  22"
echo -e "\033[1;33m◈ SSL      ⌁\033[1;37m  443"
echo -e "\033[1;33m◈ Squid    ⌁\033[1;37m  8080"
echo -e "\033[1;33m◈ DropBear ⌁\033[1;37m  80"
echo -e "\033[1;33m◈ BadVPN   ⌁\033[1;37m  7300"
echo -e ""
echo -e "   \033[1;35m◈───⪧ONLINE USER COUNT⪦────◈\033[0m"
echo -e ""
echo -e " \033[1;36mhttp://$IP:8888/server/online\033[0m"
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
