#!/bin/bash
IP=$(cat /etc/IP)
# Domain ရှိမရှိ စစ်ဆေးပြီး ရှိလျှင် Domain ကိုသုံး၊ မရှိလျှင် "No-Domain" ဟုပြမည်
[[ -f /etc/domain ]] && HOST_DOMAIN=$(cat /etc/domain) || HOST_DOMAIN="No-Domain"

cor1='\033[41;1;37m'
cor2='\033[44;1;37m'
scor='\033[0m'

newclient() {
    cp /etc/openvpn/client-common.txt ~/$1.ovpn
    echo "<ca>" >>~/$1.ovpn
    cat /etc/openvpn/easy-rsa/pki/ca.crt >>~/$1.ovpn
    echo "</ca>" >>~/$1.ovpn
    echo "<cert>" >>~/$1.ovpn
    cat /etc/openvpn/easy-rsa/pki/issued/$1.crt >>~/$1.ovpn
    echo "</cert>" >>~/$1.ovpn
    echo "<key>" >>~/$1.ovpn
    cat /etc/openvpn/easy-rsa/pki/private/$1.key >>~/$1.ovpn
    echo "</key>" >>~/$1.ovpn
    echo "<tls-auth>" >>~/$1.ovpn
    cat /etc/openvpn/ta.key >>~/$1.ovpn
    echo "</tls-auth>" >>~/$1.ovpn
}

fun_geraovpn() {
    [[ "$respost" = @(s|S) ]] && {
        cd /etc/openvpn/easy-rsa/
        ./easyrsa build-client-full $username nopass
        newclient "$username"
        sed -e "s;auth-user-pass;<auth-user-pass>\n$username\n$password\n</auth-user-pass>;g" /root/$username.ovpn >/root/tmp.ovpn && mv -f /root/tmp.ovpn /root/$username.ovpn
    } || {
        cd /etc/openvpn/easy-rsa/
        ./easyrsa build-client-full $username nopass
        newclient "$username"
    }
} >/dev/null 2>&1

clear
echo -e "\E[44;1;37m           CREATE SSH USER           \E[0m"
echo ""
echo -ne "\033[1;32m◈ Username    : \033[1;37m"; read nome
while [[ -z $nome ]]; do
    echo -e "\n\033[1;31mInvalid Username!\033[0m"
    echo -ne "\033[1;32m◈ Username    : \033[1;37m"; read nome
done
echo -ne "\033[1;32m◈ Password    : \033[1;37m"; read senha
while [[ -z $senha ]]; do
    echo -e "\n\033[1;31mInvalid Password!\033[0m"
    echo -ne "\033[1;32m◈ Password    : \033[1;37m"; read senha
done
echo -ne "\033[1;32m◈ Login Limit : \033[1;37m"; read limite
while [[ -z $limite ]] || [[ ! $limite =~ ^[0-9]+$ ]]; do
    echo -e "\n\033[1;31mInvalid Limit!\033[0m"
    echo -ne "\033[1;32m◈ Login Limit : \033[1;37m"; read limite
done
echo -ne "\033[1;32m◈ Expire Days : \033[1;37m"; read dias
while [[ -z $dias ]] || [[ ! $dias =~ ^[0-9]+$ ]]; do
    echo -e "\n\033[1;31mInvalid Days!\033[0m"
    echo -ne "\033[1;32m◈ Expire Days : \033[1;37m"; read dias
done

validade=$(date '+%C%y-%m-%d' -d " +$dias days")
validade2=$(date '+%d/%m/%Y' -d " +$dias days")

echo -e "\n\033[1;33mCREATING USER $nome...\033[0m"
useradd -M -s /bin/false -e $validade $nome > /dev/null 2>&1
echo "$nome:$senha" | chpasswd > /dev/null 2>&1
echo "$nome $limite" >> /root/usuarios.db
sleep 1.5

clear
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[1;32mThu Ya Zaw◈Sshအကောင့်ဖန်တီးပြီးပါပြီခင်ဗျာ\033[0m"
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[1;33m◈ Servers     :⪧ \033[1;37m🇹🇭⪧ Thailand ⪦🇹🇭\033[0m"
echo -e "\033[1;33m◈ IP Address  :⪧ \033[1;37m$IP\033[0m"
echo -e "\033[1;33m◈ Domain      :⪧ \033[1;37m$HOST_DOMAIN\033[0m"
echo -e "\033[1;33m◈ Username    :⪧ \033[1;37m$nome\033[0m"
echo -e "\033[1;33m◈ Password    :⪧ \033[1;37m$senha\033[0m"
echo -e "\033[1;33m◈ Login Limit :⪧ \033[1;37m$limite\033[0m"
echo -e "\033[1;33m◈ Expire Date :⪧ \033[1;37m$validade2\033[0m"
echo ""
echo -e "\033[1;35m ◈──────⪧ PORTS ⪦────◈\033[0m"
echo ""
echo -e "\033[1;32m           ◈ SSH      ⌁  22\033[0m"
echo ""
echo -e "\033[1;32m           ◈ SSL      ⌁  443\033[0m"
echo ""
echo -e "\033[1;32m          ◈ Squid    ⌁  8080\033[0m"
echo ""
echo -e "\033[1;32m          ◈ DropBear ⌁  80\033[0m"
echo ""
echo -e "\033[1;32m          ◈ BadVPN   ⌁  7300\033[0m"
echo ""
echo -e "\033[1;35m ◈───⪧Facebook Link⪦────◈\033[0m"
echo -e "\033[1;33m              ⏬⏬⏬⏬⏬⏬\033[0m"
echo -e "\033[1;36m   ━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[1;37mhttps://www.facebook.com/share/17H5fyU3iE/\033[0m"
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo ""
