#!/bin/bash
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
[[ ! -e /usr/lib/sshplus ]] && rm -rf /bin/menu > /dev/null 2>&1
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "\033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "\033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
IP=$(cat /etc/IP 2>/dev/null || wget -qO- ipv4.icanhazip.com 2>/dev/null)
x="ok"
menu ()
{
velocity () {
aguarde () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
[[ ! -d /etc/SSHPlus ]] && rm -rf /bin/menu
${comando[0]} > /dev/null 2>&1
${comando[1]} > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
fun_tst () {
speedtest --share > speed
}
echo ""
echo -e "   \033[1;32mTESTANDO A VELOCIDADE DO SERVIDOR !\033[0m"
echo ""
aguarde 'fun_tst'
echo ""
png=$(cat speed | sed -n '5 p' |awk -F : {'print $NF'})
down=$(cat speed | sed -n '7 p' |awk -F :  {'print $NF'})
upl=$(cat speed | sed -n '9 p' |awk -F :  {'print $NF'})
lnk=$(cat speed | sed -n '10 p' |awk {'print $NF'})
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[1;35m◈ \033[1;32mPING (LATENCIA):\033[1;37m$png"
echo -e "\033[1;35m◈ \033[1;32mDOWNLOAD:\033[1;37m$down"
echo -e "\033[1;35m◈ \033[1;32mUPLOAD:\033[1;37m$upl"
echo -e "\033[1;35m◈ \033[1;32mLINK: \033[1;36m$lnk\033[0m"
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
rm -rf $HOME/speed
}
#limiter
function limit1 () {
   clear
   echo -e "\n\033[1;32mINICIANDO O LIMITER... \033[0m"
   echo ""
   fun_bar 'screen -dmS limiter limiter' 'sleep 3'
   [[ $(grep -wc "limiter" /etc/autostart) = '0' ]] && {
       echo -e "ps x | grep 'limiter' | grep -v 'grep' && echo 'ON' || screen -dmS limiter limiter" >> /etc/autostart
   }
   echo -e "\n\033[1;32m  LIMITER ATIVO !\033[0m"
   sleep 3; menu
}
function limit2 () {
   clear
   echo -e "\033[1;32mPARANDO O LIMITER... \033[0m"
   echo ""
   fun_stplimiter () {
      screen -r -S "limiter" -X quit; screen -wipe 1>/dev/null 2>/dev/null
      sed -i '/limiter/d' /etc/autostart
   }
   fun_bar 'fun_stplimiter' 'sleep 3'
   echo -e "\n\033[1;31m LIMITER PARADO !\033[0m"
   sleep 3; menu
}
function limit_ssh () {
[[ $(ps x | grep "limiter"|grep -v grep |wc -l) = '0' ]] && limit1 || limit2
}

function autoexec () {
   if grep "menu;" /etc/profile > /dev/null; then
      clear; sed -i '/menu;/d' /etc/profile
      echo -e "\033[1;31mAUTO EXECUÇÃO DESATIVADO!\033[0m"; sleep 1.5s; menu2
   else
      clear; echo "menu;" >> /etc/profile
      echo -e "\033[1;32mAUTO EXECUÇÃO ATIVADO!\033[0m"; sleep 1.5s; menu2
   fi
}

function mudar_dns () {
   clear
   echo -e "\E[44;1;37m        🌐 DNS ပြောင်းရန် (CHANGE DNS) 🌐         \E[0m"
   echo -e "\033[1;33m[ 1 ]\033[1;37m ➔ Google DNS"
   echo -e "\033[1;33m[ 2 ]\033[1;37m ➔ Cloudflare DNS"
   echo -e "\033[1;33m[ 0 ]\033[1;37m ➔ နောက်သို့"
   read -p "➔ ရွေးချယ်ရန် : " opdns
   case $opdns in
      1) dns1="8.8.8.8"; dns2="8.8.4.4" ;;
      2) dns1="1.1.1.1"; dns2="1.0.0.1" ;;
      0) menu2 ;;
   esac
   echo "nameserver $dns1" > /etc/resolv.conf
   echo "nameserver $dns2" >> /etc/resolv.conf
   echo -e "\n\033[1;32m🎉 DNS အောင်မြင်ပါသည်!\033[0m"; sleep 2; menu2
}

menu2 (){
stsbot=$(ps x | grep "bot_plus"|grep -v grep > /dev/null && echo -e "\033[1;32m◉ " || echo -e "\033[1;31m○ ")
autm=$(grep "menu;" /etc/profile > /dev/null && echo -e "\033[1;32m◉ " || echo -e "\033[1;31m○ ")
system=$(cut -d' ' -f1 /etc/issue.net)
[[ ! -f /etc/vps_country ]] && echo $(wget -qO- ip-api.com/line?fields=country 2>/dev/null) > /etc/vps_country
_country=$(cat /etc/vps_country)
[[ -f /etc/domain ]] && _domain=$(cat /etc/domain) || _domain="No-Domain"
_ons=$(ps -x | grep sshd | grep -v root | grep priv | wc -l)
_ram=$(free -h | grep -i mem | awk {'print $2'})
_hora=$(date +%H:%M:%S)

clear
echo -e "           \033[38;5;226m███████████████████████████████\033[0m"
echo -e "           \033[38;5;40m██████████████\033[1;37m ★ \033[38;5;40m██████████████\033[0m"
echo -e "           \033[38;5;196m███████████████████████████████\033[0m"
echo -e "           \033[38;5;208m████████████\033[1;37m S S H \033[38;5;208m████████████\033[0m"
echo -e "\033[1;36m╭━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╮\033[0m"
echo -e "\033[1;36m┃\033[0;36m      \033[1;35m✦ \E[44;1;37m ZAW SSH MANAGER Edit:@Zaw-Ssh-Script \E[0m\033[1;35m✦      \033[1;36m┃\033[0m"
echo -e "\033[1;36m┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫\033[0m"
echo -e "\033[1;36m┃ \033[1;33mIP     :\033[1;37m $IP   \033[1;33mServer:\033[1;37m $_country\033[0m"
echo -e "\033[1;36m┃ \033[1;33mDomain :\033[1;36m ✦ $_domain ✦\033[0m"
echo -e "\033[1;36m┃ \033[1;33mOS     :\033[1;37m $system \033[1;33mRAM:\033[1;37m $_ram \033[1;33mTime:\033[1;37m $_hora\033[0m"
echo -e "\033[1;36m┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫\033[0m"
echo -e "\033[1;36m┃ \033[1;32m🟢 Online:\033[1;37m $_ons    \033[1;34m🔵 Status: \033[1;37mActive\033[0m"
echo -e "\033[1;36m╰━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╯\033[0m"
echo ""
echo -e "\033[1;35m[\033[1;36m21\033[1;35m] \033[1;32m◈ \033[1;37mADICIONAR HOST       \033[1;35m[\033[1;36m28\033[1;35m] \033[1;32m◈ \033[1;37mMUDAR SENHA ROOT"
echo -e "\033[1;35m[\033[1;36m22\033[1;35m] \033[1;32m◈ \033[1;37mREMOVER HOST         \033[1;35m[\033[1;36m29\033[1;35m] \033[1;32m◈ \033[1;37mAUTO EXECUCAO $autm"
echo -e "\033[1;35m[\033[1;36m23\033[1;35m] \033[1;32m◈ \033[1;37mREINICIAR SISTEMA    \033[1;35m[\033[1;36m30\033[1;35m] \033[1;32m◈ \033[1;37mATUALIZAR SCRIPT"
echo -e "\033[1;35m[\033[1;36m24\033[1;35m] \033[1;32m◈ \033[1;37mREINICIAR SERVICOS   \033[1;35m[\033[1;36m31\033[1;35m] \033[1;32m◈ \033[1;37mREMOVER SCRIPT"
echo -e "\033[1;35m[\033[1;36m25\033[1;35m] \033[1;32m◈ \033[1;37mBLOCK TORRENT        \033[1;35m[\033[1;36m32\033[1;35m] \033[1;32m◈ \033[1;33mVOLTAR \033[1;31m<<<<"
echo -e "\033[1;35m[\033[1;36m33\033[1;35m] \033[1;32m◈ \033[1;37mMUDAR DNS / SET DNS  \033[1;35m[\033[1;36m00\033[1;35m] \033[1;32m◈ \033[1;31mSAIR"
echo ""
echo -ne "\033[1;32m➔ O QUE DESEJA FAZER \033[1;33m?\033[1;37m : \033[0m"; read x
case "$x" in
   21) clear; addhost; menu2 ;;
   22) clear; delhost; menu2 ;;
   23) clear; reiniciarsistema ;;
   24) clear; reiniciarservicos; sleep 3; menu2 ;;
   28) clear; senharoot; sleep 3; menu2 ;;
   29) autoexec ;;
   30) attscript ;;
   31) clear; delscript ;;
   32) menu ;;
   33) mudar_dns ;;
   0|00) exit ;;
   *) menu2 ;;
esac
}

while true
do
_ons=$(ps -x | grep sshd | grep -v root | grep priv | wc -l)
clear
echo -e "           \033[38;5;226m███████████████████████████████\033[0m"
echo -e "           \033[38;5;40m██████████████\033[1;37m ★ \033[38;5;40m██████████████\033[0m"
echo -e "           \033[38;5;196m███████████████████████████████\033[0m"
echo -e "           \033[38;5;208m████████████\033[1;37m S S H \033[38;5;208m████████████\033[0m"
echo -e "\033[1;36m╭━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╮\033[0m"
echo -e "\033[1;36m┃\033[0;36m      \033[1;35m✦ \E[44;1;37m ZAW SSH MANAGER Edit:@Zaw-Ssh-Script \E[0m\033[1;35m✦      \033[1;36m┃\033[0m"
echo -e "\033[1;36m┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫\033[0m"
echo -e "\033[1;36m┃ \033[1;33mIP     :\033[1;37m $IP   \033[1;33mServer:\033[1;37m $_country\033[0m"
echo -e "\033[1;36m┃ \033[1;33mDomain :\033[1;36m ✦ $_domain ✦\033[0m"
echo -e "\033[1;36m┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫\033[0m"
echo -e "\033[1;36m┃ \033[1;32m🟢 Online:\033[1;37m $_ons    \033[1;34m🔵 Status: \033[1;37mActive\033[0m"
echo -e "\033[1;36m╰━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╯\033[0m"
echo ""
echo -e "\033[1;35m[\033[1;36m01\033[1;35m] \033[1;32m◈ \033[1;37mCRIAR USUARIO          \033[1;35m[\033[1;36m11\033[1;35m] \033[1;32m◈ \033[1;37mSPEEDTEST"
echo -e "\033[1;35m[\033[1;36m02\033[1;35m] \033[1;32m◈ \033[1;37mCRIAR USUARIO TESTE    \033[1;35m[\033[1;36m12\033[1;35m] \033[1;32m◈ \033[1;37mBANNER"
echo -e "\033[1;35m[\033[1;36m03\033[1;35m] \033[1;32m◈ \033[1;37mREMOVER USUARIO        \033[1;35m[\033[1;36m13\033[1;35m] \033[1;32m◈ \033[1;37mTRAFEGO"
echo -e "\033[1;35m[\033[1;36m04\033[1;35m] \033[1;32m◈ \033[1;37mMONITOR ONLINE         \033[1;35m[\033[1;36m14\033[1;35m] \033[1;32m◈ \033[1;37mOTIMIZAR"
echo -e "\033[1;35m[\033[1;36m05\033[1;35m] \033[1;32m◈ \033[1;37mMUDAR DATA             \033[1;35m[\033[1;36m15\033[1;35m] \033[1;32m◈ \033[1;37mBACKUP"
echo -e "\033[1;35m[\033[1;36m06\033[1;35m] \033[1;32m◈ \033[1;37mALTERAR LIMITE         \033[1;35m[\033[1;36m16\033[1;35m] \033[1;32m◈ \033[1;37mMEMORIA VIRTUAL"
echo -e "\033[1;35m[\033[1;36m07\033[1;35m] \033[1;32m◈ \033[1;37mMUDAR SENHA            \033[1;35m[\033[1;36m17\033[1;32m] ◈ \033[1;37mLIMITER"
echo -e "\033[1;35m[\033[1;36m08\033[1;35m] \033[1;32m◈ \033[1;37mREMOVER EXPIRADOS      \033[1;35m[\033[1;36m20\033[1;35m] \033[1;32m◈ \033[1;33mINFO VPS \033[1;36m>>>"
echo -e "\033[1;35m[\033[1;36m09\033[1;35m] \033[1;32m◈ \033[1;37mRELATORIO DE USUARIOS  \033[1;35m[\033[1;36m21\033[1;35m] \033[1;32m◈ \033[1;33mMAIS \033[1;36m>>>"
echo -e "\033[1;35m[\033[1;36m00\033[1;35m] \033[1;32m◈ \033[1;31mSAIR"
echo ""
echo -ne "\033[1;32m➔ O QUE DESEJA FAZER \033[1;33m?\033[1;37m : \033[0m"; read x
case "$x" in 
   1|01) clear; criarusuario ;;
   2|02) clear; criarteste ;;
   3|03) clear; remover ;;
   4|04) clear; sshmonitor ;;
   5|05) clear; mudardata ;;
   6|06) clear; alterarlimite ;;
   7|07) clear; alterarsenha ;;
   8|08) clear; expcleaner ;;
   9|09) clear; infousers ;;
   11) clear; velocity ;;
   12) clear; banner ;;
   13) clear; nload ;;
   14) clear; otimizar ;;
   15) userbackup ;;
   16) swapmemory ;;
   17) limit_ssh ;;
   20) clear; detalles ;;
   21) menu2 ;;
   0|00) exit ;;
   *) sleep 1 ;;
esac
done
}
menu
