#!/bin/bash
export DEBIAN_FRONTEND=noninteractive

# --- Progress Bar Function ---
fun_bar () {
comando[0]="$1"; comando[1]="$2"
 ( [[ -e $HOME/fim ]] && rm $HOME/fim; ${comando[0]} -y > /dev/null 2>&1; ${comando[1]} -y > /dev/null 2>&1; touch $HOME/fim ) > /dev/null 2>&1 &
 tput civis
 echo -ne "\033[1;33m["
 while true; do
   for((i=0; i<18; i++)); do echo -ne "\033[1;31m#"; sleep 0.1s; done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"; sleep 1s; tput cuu1; tput dl1; echo -ne "\033[1;33m["
 done
 echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
 tput cnorm
}

IP=$(wget -qO- ipv4.icanhazip.com 2>/dev/null)

# --- Menu Logic ---
menu () {
# OS, Country, Time စတာတွေကို တွက်ချက်ခြင်း
[[ ! -f /etc/vps_country ]] && echo $(wget -qO- ip-api.com/line?fields=country 2>/dev/null || echo "Unknown") > /etc/vps_country
_country=$(cat /etc/vps_country)
_system=$(cut -d' ' -f1 /etc/issue.net)
[[ -f /etc/domain ]] && _domain=$(cat /etc/domain) || _domain="No-Domain"
_hora=$(date +%H:%M:%S)
_ons=$(ps -x | grep sshd | grep -v root | grep priv | wc -l)

clear
echo -e "           \033[38;5;226m███████████████████████████████\033[0m"
echo -e "           \033[38;5;40m██████████████\033[1;37m ★ \033[38;5;40m██████████████\033[0m"
echo -e "           \033[38;5;196m███████████████████████████████\033[0m"
echo -e "           \033[38;5;208m████████████\033[1;37m S S H \033[38;5;208m████████████\033[0m"
echo -e "\033[1;36m╭━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╮\033[0m"
echo -e "\033[1;36m┃\033[0;36m      \033[1;35m✦ \E[44;1;37m ZAW SSH MANAGER Edit:@Zaw-Ssh-Script \E[0m\033[1;35m✦      \033[1;36m┃\033[0m"
echo -e "\033[1;36m┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫\033[0m"
echo -e "\033[1;36m┃ \033[1;33mIP     :\033[1;37m $IP   \033[1;33mServer:\033[1;37m $_country\033[0m"
echo -e "\033[1;36m┃ \033[1;33mDomain :\033[1;36m ✦ $_domain ✦\033[0m"
echo -e "\033[1;36m┃ \033[1;33mOS     :\033[1;37m $_system \033[1;33mTime:\033[1;37m $_hora\033[0m"
echo -e "\033[1;36m┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫\033[0m"
echo -e "\033[1;36m┃ \033[1;32m🟢 Online:\033[1;37m $_ons    \033[1;34m🔵 Status: \033[1;37mActive\033[0m"
echo -e "\033[1;36m╰━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╯\033[0m"

# --- Menu Options (အောက်က list တွေကို အကျဉ်းချုံ့ထားပေးပါတယ်) ---
echo -e "\n\033[1;35m[01] \033[1;37mCRIAR USUARIO"
echo -e "\033[1;35m[02] \033[1;37mSPEEDTEST"
echo -e "\033[1;35m[34] \033[1;37mMUDAR DNS"
echo -e "\033[1;35m[00] \033[1;31mSAIR\n"
echo -ne "\033[1;32m➔ O QUE DESEJA FAZER \033[1;33m?\033[1;37m : \033[0m"; read x

case "$x" in
   1|01) clear; echo "User logic..."; sleep 2; menu ;;
   2) clear; echo "Testing speed..."; sleep 2; menu ;;
   34) clear; mudar_dns ;; # function ရှိမှ အလုပ်လုပ်မှာပါ
   0|00) exit ;;
   *) echo "Opcao invalida"; sleep 2; menu ;;
esac
}

menu
